'''This file is part of rigol-scopegui.

   Copyright (c) 2017 Márk Vasi

   rigol-scopegui is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   rigol-scopegui is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with rigol-scopegui.  If not, see <http://www.gnu.org/licenses/>.'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scopegui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(879, 523)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plotWidget = PlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(500, 400))
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.horizontalLayout.addWidget(self.plotWidget)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.ch1Tab = QtGui.QWidget()
        self.ch1Tab.setObjectName(_fromUtf8("ch1Tab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.ch1Tab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ch1Widget = QtGui.QWidget(self.ch1Tab)
        self.ch1Widget.setObjectName(_fromUtf8("ch1Widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.ch1Widget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.ch1Offset = QtGui.QSlider(self.ch1Widget)
        self.ch1Offset.setOrientation(QtCore.Qt.Vertical)
        self.ch1Offset.setObjectName(_fromUtf8("ch1Offset"))
        self.gridLayout_3.addWidget(self.ch1Offset, 3, 0, 5, 1)
        self.label_6 = QtGui.QLabel(self.ch1Widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 9, 0, 1, 1)
        self.ch1GND = QtGui.QRadioButton(self.ch1Widget)
        self.ch1GND.setObjectName(_fromUtf8("ch1GND"))
        self.gridLayout_3.addWidget(self.ch1GND, 3, 2, 1, 1)
        self.ch1DC = QtGui.QRadioButton(self.ch1Widget)
        self.ch1DC.setObjectName(_fromUtf8("ch1DC"))
        self.gridLayout_3.addWidget(self.ch1DC, 2, 2, 1, 1)
        self.ch1AC = QtGui.QRadioButton(self.ch1Widget)
        self.ch1AC.setObjectName(_fromUtf8("ch1AC"))
        self.gridLayout_3.addWidget(self.ch1AC, 1, 2, 1, 1)
        self.ch1OffsetLe = QtGui.QLineEdit(self.ch1Widget)
        self.ch1OffsetLe.setObjectName(_fromUtf8("ch1OffsetLe"))
        self.gridLayout_3.addWidget(self.ch1OffsetLe, 9, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.ch1Widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 8, 0, 1, 1)
        self.ch1Enable = QtGui.QCheckBox(self.ch1Widget)
        self.ch1Enable.setObjectName(_fromUtf8("ch1Enable"))
        self.gridLayout_3.addWidget(self.ch1Enable, 0, 0, 1, 1)
        self.ch1FineAdj = QtGui.QCheckBox(self.ch1Widget)
        self.ch1FineAdj.setObjectName(_fromUtf8("ch1FineAdj"))
        self.gridLayout_3.addWidget(self.ch1FineAdj, 2, 0, 1, 1)
        self.ch1BWL = QtGui.QCheckBox(self.ch1Widget)
        self.ch1BWL.setObjectName(_fromUtf8("ch1BWL"))
        self.gridLayout_3.addWidget(self.ch1BWL, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.ch1Widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.ch1ScaleLe = QtGui.QLineEdit(self.ch1Widget)
        self.ch1ScaleLe.setObjectName(_fromUtf8("ch1ScaleLe"))
        self.gridLayout_3.addWidget(self.ch1ScaleLe, 8, 1, 1, 2)
        self.ch1Scale = QtGui.QDial(self.ch1Widget)
        self.ch1Scale.setMaximum(12)
        self.ch1Scale.setObjectName(_fromUtf8("ch1Scale"))
        self.gridLayout_3.addWidget(self.ch1Scale, 3, 1, 5, 1)
        self.ch1Probe = QtGui.QComboBox(self.ch1Widget)
        self.ch1Probe.setObjectName(_fromUtf8("ch1Probe"))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.ch1Probe.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.ch1Probe, 5, 2, 1, 1)
        self.label = QtGui.QLabel(self.ch1Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 4, 2, 1, 1)
        self.horizontalLayout_5.addWidget(self.ch1Widget)
        self.tabWidget.addTab(self.ch1Tab, _fromUtf8(""))
        self.ch2Tab = QtGui.QWidget()
        self.ch2Tab.setObjectName(_fromUtf8("ch2Tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.ch2Tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ch2Widget = QtGui.QWidget(self.ch2Tab)
        self.ch2Widget.setObjectName(_fromUtf8("ch2Widget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.ch2Widget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.ch2Offset = QtGui.QSlider(self.ch2Widget)
        self.ch2Offset.setOrientation(QtCore.Qt.Vertical)
        self.ch2Offset.setObjectName(_fromUtf8("ch2Offset"))
        self.gridLayout_6.addWidget(self.ch2Offset, 3, 0, 4, 1)
        self.ch2DC = QtGui.QRadioButton(self.ch2Widget)
        self.ch2DC.setObjectName(_fromUtf8("ch2DC"))
        self.gridLayout_6.addWidget(self.ch2DC, 2, 2, 1, 1)
        self.ch2AC = QtGui.QRadioButton(self.ch2Widget)
        self.ch2AC.setObjectName(_fromUtf8("ch2AC"))
        self.gridLayout_6.addWidget(self.ch2AC, 1, 2, 1, 1)
        self.ch2OffsetLe = QtGui.QLineEdit(self.ch2Widget)
        self.ch2OffsetLe.setObjectName(_fromUtf8("ch2OffsetLe"))
        self.gridLayout_6.addWidget(self.ch2OffsetLe, 8, 1, 1, 2)
        self.ch2GND = QtGui.QRadioButton(self.ch2Widget)
        self.ch2GND.setObjectName(_fromUtf8("ch2GND"))
        self.gridLayout_6.addWidget(self.ch2GND, 3, 2, 1, 1)
        self.ch2BWL = QtGui.QCheckBox(self.ch2Widget)
        self.ch2BWL.setObjectName(_fromUtf8("ch2BWL"))
        self.gridLayout_6.addWidget(self.ch2BWL, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.ch2Widget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 0, 2, 1, 1)
        self.ch2ScaleLe = QtGui.QLineEdit(self.ch2Widget)
        self.ch2ScaleLe.setObjectName(_fromUtf8("ch2ScaleLe"))
        self.gridLayout_6.addWidget(self.ch2ScaleLe, 7, 1, 1, 2)
        self.label_14 = QtGui.QLabel(self.ch2Widget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 7, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.ch2Widget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 8, 0, 1, 1)
        self.ch2Enable = QtGui.QCheckBox(self.ch2Widget)
        self.ch2Enable.setObjectName(_fromUtf8("ch2Enable"))
        self.gridLayout_6.addWidget(self.ch2Enable, 0, 0, 1, 1)
        self.ch2FineAdj = QtGui.QCheckBox(self.ch2Widget)
        self.ch2FineAdj.setObjectName(_fromUtf8("ch2FineAdj"))
        self.gridLayout_6.addWidget(self.ch2FineAdj, 2, 0, 1, 1)
        self.ch2Scale = QtGui.QDial(self.ch2Widget)
        self.ch2Scale.setMaximum(12)
        self.ch2Scale.setObjectName(_fromUtf8("ch2Scale"))
        self.gridLayout_6.addWidget(self.ch2Scale, 3, 1, 4, 1)
        self.label_2 = QtGui.QLabel(self.ch2Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 4, 2, 1, 1)
        self.ch2Probe = QtGui.QComboBox(self.ch2Widget)
        self.ch2Probe.setObjectName(_fromUtf8("ch2Probe"))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.ch2Probe.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.ch2Probe, 5, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.ch2Widget)
        self.tabWidget.addTab(self.ch2Tab, _fromUtf8(""))
        self.ch3Tab = QtGui.QWidget()
        self.ch3Tab.setObjectName(_fromUtf8("ch3Tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.ch3Tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ch3Widget = QtGui.QWidget(self.ch3Tab)
        self.ch3Widget.setObjectName(_fromUtf8("ch3Widget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.ch3Widget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.ch3DC = QtGui.QRadioButton(self.ch3Widget)
        self.ch3DC.setObjectName(_fromUtf8("ch3DC"))
        self.gridLayout_5.addWidget(self.ch3DC, 2, 2, 1, 1)
        self.ch3Offset = QtGui.QSlider(self.ch3Widget)
        self.ch3Offset.setOrientation(QtCore.Qt.Vertical)
        self.ch3Offset.setObjectName(_fromUtf8("ch3Offset"))
        self.gridLayout_5.addWidget(self.ch3Offset, 3, 0, 4, 1)
        self.ch3AC = QtGui.QRadioButton(self.ch3Widget)
        self.ch3AC.setObjectName(_fromUtf8("ch3AC"))
        self.gridLayout_5.addWidget(self.ch3AC, 1, 2, 1, 1)
        self.ch3OffsetLe = QtGui.QLineEdit(self.ch3Widget)
        self.ch3OffsetLe.setObjectName(_fromUtf8("ch3OffsetLe"))
        self.gridLayout_5.addWidget(self.ch3OffsetLe, 8, 1, 1, 2)
        self.ch3GND = QtGui.QRadioButton(self.ch3Widget)
        self.ch3GND.setObjectName(_fromUtf8("ch3GND"))
        self.gridLayout_5.addWidget(self.ch3GND, 3, 2, 1, 1)
        self.ch3BWL = QtGui.QCheckBox(self.ch3Widget)
        self.ch3BWL.setObjectName(_fromUtf8("ch3BWL"))
        self.gridLayout_5.addWidget(self.ch3BWL, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.ch3Widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 2, 1, 1)
        self.ch3ScaleLe = QtGui.QLineEdit(self.ch3Widget)
        self.ch3ScaleLe.setObjectName(_fromUtf8("ch3ScaleLe"))
        self.gridLayout_5.addWidget(self.ch3ScaleLe, 7, 1, 1, 2)
        self.label_11 = QtGui.QLabel(self.ch3Widget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.ch3Widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 8, 0, 1, 1)
        self.ch3Enable = QtGui.QCheckBox(self.ch3Widget)
        self.ch3Enable.setObjectName(_fromUtf8("ch3Enable"))
        self.gridLayout_5.addWidget(self.ch3Enable, 0, 0, 1, 1)
        self.ch3FineAdj = QtGui.QCheckBox(self.ch3Widget)
        self.ch3FineAdj.setObjectName(_fromUtf8("ch3FineAdj"))
        self.gridLayout_5.addWidget(self.ch3FineAdj, 2, 0, 1, 1)
        self.ch3Scale = QtGui.QDial(self.ch3Widget)
        self.ch3Scale.setMaximum(12)
        self.ch3Scale.setObjectName(_fromUtf8("ch3Scale"))
        self.gridLayout_5.addWidget(self.ch3Scale, 3, 1, 4, 1)
        self.ch3Probe = QtGui.QComboBox(self.ch3Widget)
        self.ch3Probe.setObjectName(_fromUtf8("ch3Probe"))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.ch3Probe.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.ch3Probe, 5, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.ch3Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 4, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.ch3Widget)
        self.tabWidget.addTab(self.ch3Tab, _fromUtf8(""))
        self.ch4Tab = QtGui.QWidget()
        self.ch4Tab.setObjectName(_fromUtf8("ch4Tab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.ch4Tab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ch4Widget = QtGui.QWidget(self.ch4Tab)
        self.ch4Widget.setObjectName(_fromUtf8("ch4Widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.ch4Widget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ch4Offset = QtGui.QSlider(self.ch4Widget)
        self.ch4Offset.setOrientation(QtCore.Qt.Vertical)
        self.ch4Offset.setObjectName(_fromUtf8("ch4Offset"))
        self.gridLayout_4.addWidget(self.ch4Offset, 3, 0, 4, 1)
        self.ch4DC = QtGui.QRadioButton(self.ch4Widget)
        self.ch4DC.setObjectName(_fromUtf8("ch4DC"))
        self.gridLayout_4.addWidget(self.ch4DC, 2, 2, 1, 1)
        self.ch4AC = QtGui.QRadioButton(self.ch4Widget)
        self.ch4AC.setObjectName(_fromUtf8("ch4AC"))
        self.gridLayout_4.addWidget(self.ch4AC, 1, 2, 1, 1)
        self.ch4OffsetLe = QtGui.QLineEdit(self.ch4Widget)
        self.ch4OffsetLe.setObjectName(_fromUtf8("ch4OffsetLe"))
        self.gridLayout_4.addWidget(self.ch4OffsetLe, 8, 1, 1, 2)
        self.ch4GND = QtGui.QRadioButton(self.ch4Widget)
        self.ch4GND.setObjectName(_fromUtf8("ch4GND"))
        self.gridLayout_4.addWidget(self.ch4GND, 3, 2, 1, 1)
        self.ch4BWL = QtGui.QCheckBox(self.ch4Widget)
        self.ch4BWL.setObjectName(_fromUtf8("ch4BWL"))
        self.gridLayout_4.addWidget(self.ch4BWL, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.ch4Widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 2, 1, 1)
        self.ch4ScaleLe = QtGui.QLineEdit(self.ch4Widget)
        self.ch4ScaleLe.setObjectName(_fromUtf8("ch4ScaleLe"))
        self.gridLayout_4.addWidget(self.ch4ScaleLe, 7, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.ch4Widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.ch4Widget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 8, 0, 1, 1)
        self.ch4Enable = QtGui.QCheckBox(self.ch4Widget)
        self.ch4Enable.setObjectName(_fromUtf8("ch4Enable"))
        self.gridLayout_4.addWidget(self.ch4Enable, 0, 0, 1, 1)
        self.ch4FineAdj = QtGui.QCheckBox(self.ch4Widget)
        self.ch4FineAdj.setObjectName(_fromUtf8("ch4FineAdj"))
        self.gridLayout_4.addWidget(self.ch4FineAdj, 2, 0, 1, 1)
        self.ch4Scale = QtGui.QDial(self.ch4Widget)
        self.ch4Scale.setMaximum(12)
        self.ch4Scale.setObjectName(_fromUtf8("ch4Scale"))
        self.gridLayout_4.addWidget(self.ch4Scale, 3, 1, 4, 1)
        self.ch4Probe = QtGui.QComboBox(self.ch4Widget)
        self.ch4Probe.setObjectName(_fromUtf8("ch4Probe"))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.ch4Probe.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.ch4Probe, 5, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.ch4Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 4, 2, 1, 1)
        self.horizontalLayout_4.addWidget(self.ch4Widget)
        self.tabWidget.addTab(self.ch4Tab, _fromUtf8(""))
        self.tbTab = QtGui.QWidget()
        self.tbTab.setObjectName(_fromUtf8("tbTab"))
        self.gridLayout = QtGui.QGridLayout(self.tbTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tbMain = QtGui.QWidget(self.tbTab)
        self.tbMain.setObjectName(_fromUtf8("tbMain"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tbMain)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_17 = QtGui.QLabel(self.tbMain)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.tbScaleLe = QtGui.QLineEdit(self.tbMain)
        self.tbScaleLe.setObjectName(_fromUtf8("tbScaleLe"))
        self.gridLayout_2.addWidget(self.tbScaleLe, 0, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.tbMain)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 1, 0, 1, 2)
        self.tbOffsetLe = QtGui.QLineEdit(self.tbMain)
        self.tbOffsetLe.setObjectName(_fromUtf8("tbOffsetLe"))
        self.gridLayout_2.addWidget(self.tbOffsetLe, 1, 2, 1, 1)
        self.tbOffset = QtGui.QSlider(self.tbMain)
        self.tbOffset.setOrientation(QtCore.Qt.Horizontal)
        self.tbOffset.setObjectName(_fromUtf8("tbOffset"))
        self.gridLayout_2.addWidget(self.tbOffset, 2, 0, 1, 3)
        self.tbScale = QtGui.QDial(self.tbMain)
        self.tbScale.setMaximum(30)
        self.tbScale.setObjectName(_fromUtf8("tbScale"))
        self.gridLayout_2.addWidget(self.tbScale, 3, 0, 1, 3)
        self.gridLayout.addWidget(self.tbMain, 2, 0, 1, 1)
        self.tbMode = QtGui.QWidget(self.tbTab)
        self.tbMode.setObjectName(_fromUtf8("tbMode"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tbMode)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_19 = QtGui.QLabel(self.tbMode)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 0, 0, 1, 1)
        self.tbYT = QtGui.QRadioButton(self.tbMode)
        self.tbYT.setObjectName(_fromUtf8("tbYT"))
        self.gridLayout_7.addWidget(self.tbYT, 1, 0, 1, 1)
        self.tbROLL = QtGui.QRadioButton(self.tbMode)
        self.tbROLL.setObjectName(_fromUtf8("tbROLL"))
        self.gridLayout_7.addWidget(self.tbROLL, 2, 0, 1, 1)
        self.tbXY = QtGui.QRadioButton(self.tbMode)
        self.tbXY.setObjectName(_fromUtf8("tbXY"))
        self.gridLayout_7.addWidget(self.tbXY, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 4, 0, 1, 1)
        self.tbXYWidget = QtGui.QWidget(self.tbMode)
        self.tbXYWidget.setObjectName(_fromUtf8("tbXYWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tbXYWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_20 = QtGui.QLabel(self.tbXYWidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout.addWidget(self.label_20)
        self.tbXChannel = QtGui.QComboBox(self.tbXYWidget)
        self.tbXChannel.setObjectName(_fromUtf8("tbXChannel"))
        self.tbXChannel.addItem(_fromUtf8(""))
        self.tbXChannel.addItem(_fromUtf8(""))
        self.tbXChannel.addItem(_fromUtf8(""))
        self.tbXChannel.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.tbXChannel)
        self.label_21 = QtGui.QLabel(self.tbXYWidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout.addWidget(self.label_21)
        self.tbYChannel = QtGui.QComboBox(self.tbXYWidget)
        self.tbYChannel.setObjectName(_fromUtf8("tbYChannel"))
        self.tbYChannel.addItem(_fromUtf8(""))
        self.tbYChannel.addItem(_fromUtf8(""))
        self.tbYChannel.addItem(_fromUtf8(""))
        self.tbYChannel.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.tbYChannel)
        self.gridLayout_7.addWidget(self.tbXYWidget, 0, 1, 5, 1)
        self.gridLayout.addWidget(self.tbMode, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tbTab, _fromUtf8(""))
        self.trgTab = QtGui.QWidget()
        self.trgTab.setObjectName(_fromUtf8("trgTab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.trgTab)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.trgMainWidget = QtGui.QWidget(self.trgTab)
        self.trgMainWidget.setObjectName(_fromUtf8("trgMainWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.trgMainWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.trgShow = QtGui.QCheckBox(self.trgMainWidget)
        self.trgShow.setObjectName(_fromUtf8("trgShow"))
        self.verticalLayout_2.addWidget(self.trgShow)
        self.label_22 = QtGui.QLabel(self.trgMainWidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_2.addWidget(self.label_22)
        self.trgEdge = QtGui.QRadioButton(self.trgMainWidget)
        self.trgEdge.setObjectName(_fromUtf8("trgEdge"))
        self.verticalLayout_2.addWidget(self.trgEdge)
        self.trgPulse = QtGui.QRadioButton(self.trgMainWidget)
        self.trgPulse.setObjectName(_fromUtf8("trgPulse"))
        self.verticalLayout_2.addWidget(self.trgPulse)
        self.trgSlope = QtGui.QRadioButton(self.trgMainWidget)
        self.trgSlope.setObjectName(_fromUtf8("trgSlope"))
        self.verticalLayout_2.addWidget(self.trgSlope)
        self.trgVideo = QtGui.QRadioButton(self.trgMainWidget)
        self.trgVideo.setObjectName(_fromUtf8("trgVideo"))
        self.verticalLayout_2.addWidget(self.trgVideo)
        self.trgPattern = QtGui.QRadioButton(self.trgMainWidget)
        self.trgPattern.setObjectName(_fromUtf8("trgPattern"))
        self.verticalLayout_2.addWidget(self.trgPattern)
        self.trgDuration = QtGui.QRadioButton(self.trgMainWidget)
        self.trgDuration.setObjectName(_fromUtf8("trgDuration"))
        self.verticalLayout_2.addWidget(self.trgDuration)
        self.label_23 = QtGui.QLabel(self.trgMainWidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_2.addWidget(self.label_23)
        self.trgAuto = QtGui.QRadioButton(self.trgMainWidget)
        self.trgAuto.setObjectName(_fromUtf8("trgAuto"))
        self.verticalLayout_2.addWidget(self.trgAuto)
        self.trgNormal = QtGui.QRadioButton(self.trgMainWidget)
        self.trgNormal.setObjectName(_fromUtf8("trgNormal"))
        self.verticalLayout_2.addWidget(self.trgNormal)
        self.trgSingle = QtGui.QRadioButton(self.trgMainWidget)
        self.trgSingle.setObjectName(_fromUtf8("trgSingle"))
        self.verticalLayout_2.addWidget(self.trgSingle)
        self.label_24 = QtGui.QLabel(self.trgMainWidget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_2.addWidget(self.label_24)
        self.trgHoldoff = QtGui.QLineEdit(self.trgMainWidget)
        self.trgHoldoff.setObjectName(_fromUtf8("trgHoldoff"))
        self.verticalLayout_2.addWidget(self.trgHoldoff)
        self.trgNoise = QtGui.QCheckBox(self.trgMainWidget)
        self.trgNoise.setObjectName(_fromUtf8("trgNoise"))
        self.verticalLayout_2.addWidget(self.trgNoise)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_6.addWidget(self.trgMainWidget)
        self.trgStackedWidget = QtGui.QStackedWidget(self.trgTab)
        self.trgStackedWidget.setObjectName(_fromUtf8("trgStackedWidget"))
        self.trgEdgeWidget = EdgeWidget()
        self.trgEdgeWidget.setObjectName(_fromUtf8("trgEdgeWidget"))
        self.trgStackedWidget.addWidget(self.trgEdgeWidget)
        self.trgPulseWidget = PulseWidget()
        self.trgPulseWidget.setObjectName(_fromUtf8("trgPulseWidget"))
        self.trgStackedWidget.addWidget(self.trgPulseWidget)
        self.trgSlopeWidget = SlopeWidget()
        self.trgSlopeWidget.setObjectName(_fromUtf8("trgSlopeWidget"))
        self.trgStackedWidget.addWidget(self.trgSlopeWidget)
        self.trgVideoWidget = VideoWidget()
        self.trgVideoWidget.setObjectName(_fromUtf8("trgVideoWidget"))
        self.trgStackedWidget.addWidget(self.trgVideoWidget)

        self.trgModeGroup = QtGui.QButtonGroup(self.trgMainWidget)
        self.trgModeGroup.addButton(self.trgEdge)
        self.trgModeGroup.addButton(self.trgPulse)
        self.trgModeGroup.addButton(self.trgSlope)
        self.trgModeGroup.addButton(self.trgVideo)
        self.trgModeGroup.addButton(self.trgPattern)
        self.trgModeGroup.addButton(self.trgDuration)
        
        self.horizontalLayout_6.addWidget(self.trgStackedWidget)
        self.tabWidget.addTab(self.trgTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 879, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menuBar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menuFunction = QtGui.QMenu(self.menuBar)
        self.menuFunction.setObjectName(_fromUtf8("menuFunction"))
        MainWindow.setMenuBar(self.menuBar)
        self.action_Save_configuration = QtGui.QAction(MainWindow)
        self.action_Save_configuration.setObjectName(_fromUtf8("action_Save_configuration"))
        self.action_Load_configuration = QtGui.QAction(MainWindow)
        self.action_Load_configuration.setObjectName(_fromUtf8("action_Load_configuration"))
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.actionIP_Adress = QtGui.QAction(MainWindow)
        self.actionIP_Adress.setObjectName(_fromUtf8("actionIP_Adress"))
        self.actionDefault_configuration = QtGui.QAction(MainWindow)
        self.actionDefault_configuration.setObjectName(_fromUtf8("actionDefault_configuration"))
        self.actionLoad_current_settings_from_scope = QtGui.QAction(MainWindow)
        self.actionLoad_current_settings_from_scope.setObjectName(_fromUtf8("actionLoad_current_settings_from_scope"))
        self.action_Run = QtGui.QAction(MainWindow)
        self.action_Run.setObjectName(_fromUtf8("action_Run"))
        self.action_Stop = QtGui.QAction(MainWindow)
        self.action_Stop.setObjectName(_fromUtf8("action_Stop"))
        self.action_Autoset = QtGui.QAction(MainWindow)
        self.action_Autoset.setObjectName(_fromUtf8("action_Autoset"))
        self.menu_File.addAction(self.action_Save_configuration)
        self.menu_File.addAction(self.action_Load_configuration)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionLoad_current_settings_from_scope)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Edit.addAction(self.actionIP_Adress)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionDefault_configuration)
        self.menuFunction.addAction(self.action_Run)
        self.menuFunction.addAction(self.action_Stop)
        self.menuFunction.addAction(self.action_Autoset)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Edit.menuAction())
        self.menuBar.addAction(self.menuFunction.menuAction())
        self.label_6.setBuddy(self.ch1OffsetLe)
        self.label_5.setBuddy(self.ch1ScaleLe)
        self.label_14.setBuddy(self.ch2ScaleLe)
        self.label_15.setBuddy(self.ch2OffsetLe)
        self.label_11.setBuddy(self.ch3ScaleLe)
        self.label_12.setBuddy(self.ch3OffsetLe)
        self.label_8.setBuddy(self.ch4ScaleLe)
        self.label_9.setBuddy(self.ch4OffsetLe)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        self.trgStackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.plotWidget, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.ch1Enable)
        MainWindow.setTabOrder(self.ch1Enable, self.ch1BWL)
        MainWindow.setTabOrder(self.ch1BWL, self.ch1FineAdj)
        MainWindow.setTabOrder(self.ch1FineAdj, self.ch1AC)
        MainWindow.setTabOrder(self.ch1AC, self.ch1DC)
        MainWindow.setTabOrder(self.ch1DC, self.ch1GND)
        MainWindow.setTabOrder(self.ch1GND, self.ch1Offset)
        MainWindow.setTabOrder(self.ch1Offset, self.ch1Scale)
        MainWindow.setTabOrder(self.ch1Scale, self.ch1ScaleLe)
        MainWindow.setTabOrder(self.ch1ScaleLe, self.ch1OffsetLe)
        MainWindow.setTabOrder(self.ch1OffsetLe, self.ch2Enable)
        MainWindow.setTabOrder(self.ch2Enable, self.ch2BWL)
        MainWindow.setTabOrder(self.ch2BWL, self.ch2FineAdj)
        MainWindow.setTabOrder(self.ch2FineAdj, self.ch2AC)
        MainWindow.setTabOrder(self.ch2AC, self.ch2DC)
        MainWindow.setTabOrder(self.ch2DC, self.ch2GND)
        MainWindow.setTabOrder(self.ch2GND, self.ch2Offset)
        MainWindow.setTabOrder(self.ch2Offset, self.ch2Scale)
        MainWindow.setTabOrder(self.ch2Scale, self.ch2ScaleLe)
        MainWindow.setTabOrder(self.ch2ScaleLe, self.ch2OffsetLe)
        MainWindow.setTabOrder(self.ch2OffsetLe, self.ch3Enable)
        MainWindow.setTabOrder(self.ch3Enable, self.ch3BWL)
        MainWindow.setTabOrder(self.ch3BWL, self.ch3FineAdj)
        MainWindow.setTabOrder(self.ch3FineAdj, self.ch3AC)
        MainWindow.setTabOrder(self.ch3AC, self.ch3DC)
        MainWindow.setTabOrder(self.ch3DC, self.ch3GND)
        MainWindow.setTabOrder(self.ch3GND, self.ch3Offset)
        MainWindow.setTabOrder(self.ch3Offset, self.ch3Scale)
        MainWindow.setTabOrder(self.ch3Scale, self.ch3ScaleLe)
        MainWindow.setTabOrder(self.ch3ScaleLe, self.ch3OffsetLe)
        MainWindow.setTabOrder(self.ch3OffsetLe, self.ch4Enable)
        MainWindow.setTabOrder(self.ch4Enable, self.ch4BWL)
        MainWindow.setTabOrder(self.ch4BWL, self.ch4FineAdj)
        MainWindow.setTabOrder(self.ch4FineAdj, self.ch4AC)
        MainWindow.setTabOrder(self.ch4AC, self.ch4DC)
        MainWindow.setTabOrder(self.ch4DC, self.ch4GND)
        MainWindow.setTabOrder(self.ch4GND, self.ch4Offset)
        MainWindow.setTabOrder(self.ch4Offset, self.ch4Scale)
        MainWindow.setTabOrder(self.ch4Scale, self.ch4ScaleLe)
        MainWindow.setTabOrder(self.ch4ScaleLe, self.ch4OffsetLe)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_6.setText(_translate("MainWindow", "Offset", None))
        self.ch1GND.setText(_translate("MainWindow", "GND", None))
        self.ch1DC.setText(_translate("MainWindow", "DC", None))
        self.ch1AC.setText(_translate("MainWindow", "AC", None))
        self.label_5.setText(_translate("MainWindow", "Scale", None))
        self.ch1Enable.setText(_translate("MainWindow", "Enable", None))
        self.ch1FineAdj.setText(_translate("MainWindow", "Fine adjustment", None))
        self.ch1BWL.setText(_translate("MainWindow", "20M BW limit", None))
        self.label_4.setText(_translate("MainWindow", "Coupling", None))
        self.ch1Probe.setItemText(0, _translate("MainWindow", "0.01", None))
        self.ch1Probe.setItemText(1, _translate("MainWindow", "0.02", None))
        self.ch1Probe.setItemText(2, _translate("MainWindow", "0.05", None))
        self.ch1Probe.setItemText(3, _translate("MainWindow", "0.1", None))
        self.ch1Probe.setItemText(4, _translate("MainWindow", "0.2", None))
        self.ch1Probe.setItemText(5, _translate("MainWindow", "0.5", None))
        self.ch1Probe.setItemText(6, _translate("MainWindow", "1", None))
        self.ch1Probe.setItemText(7, _translate("MainWindow", "2", None))
        self.ch1Probe.setItemText(8, _translate("MainWindow", "5", None))
        self.ch1Probe.setItemText(9, _translate("MainWindow", "10", None))
        self.ch1Probe.setItemText(10, _translate("MainWindow", "20", None))
        self.ch1Probe.setItemText(11, _translate("MainWindow", "50", None))
        self.ch1Probe.setItemText(12, _translate("MainWindow", "100", None))
        self.ch1Probe.setItemText(13, _translate("MainWindow", "200", None))
        self.ch1Probe.setItemText(14, _translate("MainWindow", "500", None))
        self.ch1Probe.setItemText(15, _translate("MainWindow", "1000", None))
        self.label.setText(_translate("MainWindow", "Probe", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ch1Tab), _translate("MainWindow", "Channel 1", None))
        self.ch2DC.setText(_translate("MainWindow", "DC", None))
        self.ch2AC.setText(_translate("MainWindow", "AC", None))
        self.ch2GND.setText(_translate("MainWindow", "GND", None))
        self.ch2BWL.setText(_translate("MainWindow", "20M BW limit", None))
        self.label_13.setText(_translate("MainWindow", "Coupling", None))
        self.label_14.setText(_translate("MainWindow", "Scale", None))
        self.label_15.setText(_translate("MainWindow", "Offset", None))
        self.ch2Enable.setText(_translate("MainWindow", "Enable", None))
        self.ch2FineAdj.setText(_translate("MainWindow", "Fine adjustment", None))
        self.label_2.setText(_translate("MainWindow", "Probe", None))
        self.ch2Probe.setItemText(0, _translate("MainWindow", "0.01", None))
        self.ch2Probe.setItemText(1, _translate("MainWindow", "0.02", None))
        self.ch2Probe.setItemText(2, _translate("MainWindow", "0.05", None))
        self.ch2Probe.setItemText(3, _translate("MainWindow", "0.1", None))
        self.ch2Probe.setItemText(4, _translate("MainWindow", "0.2", None))
        self.ch2Probe.setItemText(5, _translate("MainWindow", "0.5", None))
        self.ch2Probe.setItemText(6, _translate("MainWindow", "1", None))
        self.ch2Probe.setItemText(7, _translate("MainWindow", "2", None))
        self.ch2Probe.setItemText(8, _translate("MainWindow", "5", None))
        self.ch2Probe.setItemText(9, _translate("MainWindow", "10", None))
        self.ch2Probe.setItemText(10, _translate("MainWindow", "20", None))
        self.ch2Probe.setItemText(11, _translate("MainWindow", "50", None))
        self.ch2Probe.setItemText(12, _translate("MainWindow", "100", None))
        self.ch2Probe.setItemText(13, _translate("MainWindow", "200", None))
        self.ch2Probe.setItemText(14, _translate("MainWindow", "500", None))
        self.ch2Probe.setItemText(15, _translate("MainWindow", "1000", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ch2Tab), _translate("MainWindow", "Channel 2", None))
        self.ch3DC.setText(_translate("MainWindow", "DC", None))
        self.ch3AC.setText(_translate("MainWindow", "AC", None))
        self.ch3GND.setText(_translate("MainWindow", "GND", None))
        self.ch3BWL.setText(_translate("MainWindow", "20M BW limit", None))
        self.label_10.setText(_translate("MainWindow", "Coupling", None))
        self.label_11.setText(_translate("MainWindow", "Scale", None))
        self.label_12.setText(_translate("MainWindow", "Offset", None))
        self.ch3Enable.setText(_translate("MainWindow", "Enable", None))
        self.ch3FineAdj.setText(_translate("MainWindow", "Fine adjustment", None))
        self.ch3Probe.setItemText(0, _translate("MainWindow", "0.01", None))
        self.ch3Probe.setItemText(1, _translate("MainWindow", "0.02", None))
        self.ch3Probe.setItemText(2, _translate("MainWindow", "0.05", None))
        self.ch3Probe.setItemText(3, _translate("MainWindow", "0.1", None))
        self.ch3Probe.setItemText(4, _translate("MainWindow", "0.2", None))
        self.ch3Probe.setItemText(5, _translate("MainWindow", "0.5", None))
        self.ch3Probe.setItemText(6, _translate("MainWindow", "1", None))
        self.ch3Probe.setItemText(7, _translate("MainWindow", "2", None))
        self.ch3Probe.setItemText(8, _translate("MainWindow", "5", None))
        self.ch3Probe.setItemText(9, _translate("MainWindow", "10", None))
        self.ch3Probe.setItemText(10, _translate("MainWindow", "20", None))
        self.ch3Probe.setItemText(11, _translate("MainWindow", "50", None))
        self.ch3Probe.setItemText(12, _translate("MainWindow", "100", None))
        self.ch3Probe.setItemText(13, _translate("MainWindow", "200", None))
        self.ch3Probe.setItemText(14, _translate("MainWindow", "500", None))
        self.ch3Probe.setItemText(15, _translate("MainWindow", "1000", None))
        self.label_3.setText(_translate("MainWindow", "Probe", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ch3Tab), _translate("MainWindow", "Channel 3", None))
        self.ch4DC.setText(_translate("MainWindow", "DC", None))
        self.ch4AC.setText(_translate("MainWindow", "AC", None))
        self.ch4GND.setText(_translate("MainWindow", "GND", None))
        self.ch4BWL.setText(_translate("MainWindow", "20M BW limit", None))
        self.label_7.setText(_translate("MainWindow", "Coupling", None))
        self.label_8.setText(_translate("MainWindow", "Scale", None))
        self.label_9.setText(_translate("MainWindow", "Offset", None))
        self.ch4Enable.setText(_translate("MainWindow", "Enable", None))
        self.ch4FineAdj.setText(_translate("MainWindow", "Fine adjustment", None))
        self.ch4Probe.setItemText(0, _translate("MainWindow", "0.01", None))
        self.ch4Probe.setItemText(1, _translate("MainWindow", "0.02", None))
        self.ch4Probe.setItemText(2, _translate("MainWindow", "0.05", None))
        self.ch4Probe.setItemText(3, _translate("MainWindow", "0.1", None))
        self.ch4Probe.setItemText(4, _translate("MainWindow", "0.2", None))
        self.ch4Probe.setItemText(5, _translate("MainWindow", "0.5", None))
        self.ch4Probe.setItemText(6, _translate("MainWindow", "1", None))
        self.ch4Probe.setItemText(7, _translate("MainWindow", "2", None))
        self.ch4Probe.setItemText(8, _translate("MainWindow", "5", None))
        self.ch4Probe.setItemText(9, _translate("MainWindow", "10", None))
        self.ch4Probe.setItemText(10, _translate("MainWindow", "20", None))
        self.ch4Probe.setItemText(11, _translate("MainWindow", "50", None))
        self.ch4Probe.setItemText(12, _translate("MainWindow", "100", None))
        self.ch4Probe.setItemText(13, _translate("MainWindow", "200", None))
        self.ch4Probe.setItemText(14, _translate("MainWindow", "500", None))
        self.ch4Probe.setItemText(15, _translate("MainWindow", "1000", None))
        self.label_16.setText(_translate("MainWindow", "Probe", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ch4Tab), _translate("MainWindow", "Channel 4", None))
        self.label_17.setText(_translate("MainWindow", "Scale", None))
        self.label_18.setText(_translate("MainWindow", "Offset", None))
        self.label_19.setText(_translate("MainWindow", "MODE", None))
        self.tbYT.setText(_translate("MainWindow", "YT", None))
        self.tbROLL.setText(_translate("MainWindow", "ROLL", None))
        self.tbXY.setText(_translate("MainWindow", "XY", None))
        self.label_20.setText(_translate("MainWindow", "X Channel", None))
        self.tbXChannel.setItemText(0, _translate("MainWindow", "CH1", None))
        self.tbXChannel.setItemText(1, _translate("MainWindow", "CH2", None))
        self.tbXChannel.setItemText(2, _translate("MainWindow", "CH3", None))
        self.tbXChannel.setItemText(3, _translate("MainWindow", "CH4", None))
        self.label_21.setText(_translate("MainWindow", "Y Channel", None))
        self.tbYChannel.setItemText(0, _translate("MainWindow", "CH1", None))
        self.tbYChannel.setItemText(1, _translate("MainWindow", "CH2", None))
        self.tbYChannel.setItemText(2, _translate("MainWindow", "CH3", None))
        self.tbYChannel.setItemText(3, _translate("MainWindow", "CH4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbTab), _translate("MainWindow", "Timebase", None))
        self.trgShow.setText(_translate("MainWindow", "Show Trigger", None))
        self.label_22.setText(_translate("MainWindow", "Type", None))
        self.trgEdge.setText(_translate("MainWindow", "Edge", None))
        self.trgPulse.setText(_translate("MainWindow", "Pulse", None))
        self.trgSlope.setText(_translate("MainWindow", "Slope", None))
        self.trgVideo.setText(_translate("MainWindow", "Video", None))
        self.trgPattern.setText(_translate("MainWindow", "Pattern", None))
        self.trgDuration.setText(_translate("MainWindow", "Duration", None))
        self.label_23.setText(_translate("MainWindow", "Sweep", None))
        self.trgAuto.setText(_translate("MainWindow", "Auto", None))
        self.trgNormal.setText(_translate("MainWindow", "Normal", None))
        self.trgSingle.setText(_translate("MainWindow", "Single", None))
        self.label_24.setText(_translate("MainWindow", "Holdoff", None))
        self.trgNoise.setText(_translate("MainWindow", "Noise Rejection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trgTab), _translate("MainWindow", "Trigger", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menuFunction.setTitle(_translate("MainWindow", "Function", None))
        self.action_Save_configuration.setText(_translate("MainWindow", "&Save configuration", None))
        self.action_Load_configuration.setText(_translate("MainWindow", "&Open configuration", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.actionIP_Adress.setText(_translate("MainWindow", "IP Adress", None))
        self.actionDefault_configuration.setText(_translate("MainWindow", "Default configuration", None))
        self.actionLoad_current_settings_from_scope.setText(_translate("MainWindow", "Load current settings from scope", None))
        self.action_Run.setText(_translate("MainWindow", "&Run", None))
        self.action_Stop.setText(_translate("MainWindow", "&Stop", None))
        self.action_Autoset.setText(_translate("MainWindow", "&Autoset", None))

from pyqtgraph import PlotWidget
from triggerWidgets import EdgeWidget, PulseWidget, SlopeWidget, VideoWidget
